---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.fullname" . }}-sandbox-config
data:
  python-requirements.txt: |
{{ .Values.sandbox.config.python_requirements | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.fullname" . }}-env-config
  labels:
    {{- include "dify.labels" . | nindent 4 }}
data:
  {{- if .Values.globalEnv }}
  {{- range $key, $value := .Values.globalEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}