{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laminar.fullname" . }}-qdrant
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "laminar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: qdrant
  template:
    metadata:
      labels:
        {{- include "laminar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: qdrant
          image: {{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}
          imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
        {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "laminar.fullname" . }}-qdrant
        {{- else }}
          emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laminar.fullname" . }}-qdrant
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: {{ .Values.qdrant.service.type }}
  ports:
    - port: {{ .Values.qdrant.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "laminar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- if and .Values.qdrant.enabled .Values.qdrant.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laminar.fullname" . }}-qdrant
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
{{- end }}
{{- end }}
