apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laminar.fullname" . }}-secrets
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
type: Opaque
data:
  sharedSecretToken: {{ .Values.appServer.env.sharedSecretToken | b64enc | quote }}
  aeadSecretKey: {{ .Values.appServer.env.aeadSecretKey | b64enc | quote }}
  cohereApiKey: {{ .Values.semanticSearchService.env.cohereApiKey | b64enc | quote }}
  nextauthSecret: {{ .Values.frontend.env.nextauthSecret | b64enc | quote }}
